version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
  backend:
    depends_on:
      - serviceName: db
    build: ./backend
    ports:
      - 3000:3000
  frontend:
    depends_on:
      - serviceName: backend
    build: ./frontend
    ports:
      - 80:80